import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";

import FirebaseAuthSync from "@/shared/components/FirebaseAuthSync";

import "./globals.css";

export const metadata: Metadata = {
  title: "NexusNotes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="flex min-h-screen flex-col">
          <FirebaseAuthSync />
          {children}
          <Toaster
            position="bottom-right"
            richColors
            expand={true}
            duration={2000}
            visibleToasts={3}
            toastOptions={{
              classNames: {
                toast: "!border-none",
                error: "!bg-red-600 !text-white",
                success: "!bg-green-600 !text-white",
                info: "!bg-blue-600 !text-white",
              },
            }}
          />
        </body>
      </html>
    </ClerkProvider>
  );
}
